## 5. <strong>NumPy 배열</strong>

In [ ]:
# Python 패키지 설치 명령어
!pip install numpy

In [1]:
# NumPy 불러오기
import numpy as np

### <strong> 5.1 NumPy 배열 생성

In [2]:
# [+] 리스트 객체로부터 ndarray 객체 생성
my_lst = [1,2,3,4,5,6]
my_lst = np.array(my_lst)
print(my_lst)

[1 2 3 4 5 6]


In [3]:
# [+] 리스트/NumPy 배열 동시에 생성
my_lst = np.array([1,2,3,4,5,6])

#### 리스트 컴프리헨션 vs NumPy 배열

In [4]:
prices = [20, 40, 35, 10, 25, 56]

# [+] 리스트 컴프리헨션을 이용하여 5달러씩 할인된 가격 리스트를 생성
new_prices = [price-5 for price in prices]
print(new_prices)

# [+] NumPy 배열의 연산을 통한 5달러씩 할인된 가격 리스트를 생성
prices_arr = np.array(prices)
prices_arr -= 5
print(prices_arr)

[15, 35, 30, 5, 20, 51]
[15 35 30  5 20 51]


#### 예제: 시험 점수 처리

In [5]:
# 세 번의 시험에 대한 점수를 NumPy 배열로 선언
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

In [7]:
# [+] 세 번째 시험에 2점씩 더하기
test_3_fixed = np.array(test_3)
test_3_fixed += 2
print(test_3_fixed)

[89 87 74 92 94]


In [8]:
# [+] 학생 별 전체 시험 점수 총합 계산 -> total_grade
total_grade = np.array(test_1 + test_2 + test_3_fixed)
print(total_grade)

[260 281 248 276 272]


In [9]:
# [+] 학생 별 평균 시험 점수 계산 -> final_grade
final_grade = np.array(total_grade/3)
print(final_grade)

[86.66666667 93.66666667 82.66666667 92.         90.66666667]


In [10]:
# [+] 인덱싱: Jeremy의 두 번째 시험 점수
jeremy_test_2 = test_2[3]
print(jeremy_test_2)

93


In [11]:
# [+] Manual과 Adwoa의 첫 번째 시험 점수
manual_adwoa_test_1 = test_1[1:3]
print(manual_adwoa_test_1)

[94 88]


In [12]:
# [+] 전체 학생들의 점수를 2차원 배열에 저장 -> student_scores
student_scores = np.array([test_1, test_2, test_3_fixed])
print(student_scores)

[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 89  87  74  92  94]]


In [13]:
# [+] 2차원 배열 인덱싱: Tanya의 세 번째 시험 점수
print(student_scores[2,0])

# [+] 2차원 배열 슬라이싱: Cody의 전체 시험 점수
print(student_scores[:,4])

89
[87 91 94]


#### 배열 원소 단위의 논리 연산

In [14]:
a = np.array([1, 20, 4, 6, 28, 88, 7, 12])

# [+] 15 이상 여부를 마스킹
mask = a >= 15
print(mask)

[False  True False False  True  True False False]


In [15]:
# [+] 논리 연산을 이용하여 부분집합 구하기
selected = a[a > 5]
print(selected)

[20  6 28 88  7 12]


In [16]:
# [+] 논리식 결합: 논리합
selected = a[(a > 5) | (a < 3)]
print(selected)

[ 1 20  6 28 88  7 12]


In [17]:
# [+] 논리식 결합: 논리곱
selected = a[(a > 5) & (a < 15)]
print(selected)

[ 6  7 12]


In [18]:
# [+] 정수 배열 생성
np.arange(20)
np.arange(10,20) #10부터 20까지
np.arange(10,20,3) #3의 간격

array([10, 13, 16, 19])

In [19]:
# [+] 난수 배열 생성
np.random.seed(5)
arr = np.random.randint(10, size=(3, 5))
print(arr)

[[3 6 6 0 9]
 [8 4 7 0 0]
 [7 1 5 7 0]]


In [20]:
porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])

In [21]:
cold = porridge[porridge < 60]
print(cold)

[50 56 51]


In [22]:
hot = porridge[porridge > 80]
print(hot)

[90 85 98]


In [23]:
just_right = porridge[(porridge <= 80)&(porridge >= 60)]
print(just_right)

[79 65 63 79]


### <strong>5.2 배열 조작 연산</strong>

In [24]:
arr = np.random.randint(10, size = (3,5))
arr

array([[1, 4, 6, 2, 9],
       [9, 9, 9, 1, 2],
       [7, 0, 5, 0, 0]])

In [25]:
# [+] 배열 속성
print(arr.ndim)     # 차원 수
print(arr.shape)    # 형상
print(arr.size)     # 크기(원소의 개수)
print(arr.dtype)    # 데이터 타입
print(arr.itemsize) # 원소별 메모리 크기(bytes)
print(arr.nbytes)   # 전체 메모리 크기

2
(3, 5)
15
int32
4
60


In [26]:
# [+] 배열 슬라이싱
arr = np.arange(10)
print(arr)

print(arr[3:7])
print(arr[:5])
print(arr[5:])
print(arr[::3]) #처음부터 끝까지 3칸씩
print(arr[2:8:2]) #2부터 7까지 2칸씩

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[0 1 2 3 4]
[5 6 7 8 9]
[0 3 6 9]
[2 4 6]


In [27]:
np.random.seed(0)
arr = np.random.randint(10, size=(6, 8))
arr

array([[5, 0, 3, 3, 7, 9, 3, 5],
       [2, 4, 7, 6, 8, 8, 1, 6],
       [7, 7, 8, 1, 5, 9, 8, 9],
       [4, 3, 0, 3, 5, 0, 2, 3],
       [8, 1, 3, 3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7, 3, 2, 7]])

In [28]:
# [+] 다차원 배열 슬라이싱
arr[3:5, 4:7] #[행, 열]

array([[5, 0, 2],
       [3, 7, 0]])

In [29]:
np.random.seed(0)
arr = np.random.randint(10, size = (5,7))
arr

array([[5, 0, 3, 3, 7, 9, 3],
       [5, 2, 4, 7, 6, 8, 8],
       [1, 6, 7, 7, 8, 1, 5],
       [9, 8, 9, 4, 3, 0, 3],
       [5, 0, 2, 3, 8, 1, 3]])

In [30]:
arr[:2, :3]

array([[5, 0, 3],
       [5, 2, 4]])

In [31]:
arr[:3, ::2]

array([[5, 3, 7, 3],
       [5, 4, 6, 8],
       [1, 7, 8, 5]])

In [32]:
np.random.seed(0)
arr = np.random.randint(10, size=(3, 4))
print(arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [33]:
# 배열 슬라이스 = 뷰(view)
arr_sub = arr[:2, :2]
print(arr_sub)

arr_sub[0, 0] = 99
print(arr_sub)

print(arr)

[[5 0]
 [7 9]]
[[99  0]
 [ 7  9]]
[[99  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]


In [34]:
# .copy()
arr_sub = arr[:2, :2].copy()

arr_sub[0, 0] = 99
print(arr_sub)

print(arr)

[[99  0]
 [ 7  9]]
[[99  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]


In [35]:
x = np.arange(10)
print(x, '\n')

[0 1 2 3 4 5 6 7 8 9] 



In [36]:
# [+] 배열 재구조화: reshape()
x = x.reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [37]:
arr = np.ones((3, 4))
print(arr)
print(arr.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)


In [38]:
# [+] 배열 재구조화: 차원 추가(np.newaxis)
arr_new = arr[ :, :, np.newaxis]
print(arr_new)
print(arr_new.shape)

[[[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]]
(3, 4, 1)


In [39]:
arr_1 = np.arange(1, 4)
arr_2 = np.arange(4, 7)
arr_3 = np.arange(7, 10)

print(arr_1, arr_2, arr_3)

[1 2 3] [4 5 6] [7 8 9]


In [40]:
# [+] 배열 연결: np.concatenate()
np.concatenate([arr_1, arr_2, arr_3])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
# [+] 배열 연결: 종연결 
arr_total = np.vstack([arr_1, arr_2, arr_3])
print(arr_total)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
# [+] 배열 연결: 횡연결
arr_total = np.hstack([arr_1, arr_2, arr_3])
print(arr_total)

[1 2 3 4 5 6 7 8 9]


In [43]:
arr = [1, 2, 3, 99, 99, 3, 2, 1]
print(arr)

[1, 2, 3, 99, 99, 3, 2, 1]


In [44]:
# [+] 배열 분할
arr_1, arr_2, arr_3 = np.split(arr, [3, 5])
print(arr_1, arr_2, arr_3)

[1 2 3] [99 99] [3 2 1]
