## <strong>6. NumPy: Universal Functions (UFunc)</strong>

In [1]:
import numpy as np

In [2]:
# 역수 계산 함수
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

# 함수 테스트
values = np.random.randint(1, 10, size=5)
print(values)
print(compute_reciprocals(values))

[1 4 5 1 6]
[1.         0.25       0.2        1.         0.16666667]


#### 역수 계산: Python loop vs NumPy ufuncs
+ ```%timeit```: 셀 단위 코드 실행 시간을 측정하는 매직 함수

In [3]:
# 백만 개 크기의 난수 배열 생성
big_array = np.random.randint(1, 100, size=1000000)

In [4]:
# [+] Python loop를 통한 역수 계산
%timeit compute_reciprocals(big_array)

1.93 s ± 58.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
# NumPy ufunc을 통한 벡터화된 역수 계산
%timeit 1 / big_array

2.84 ms ± 32.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### UFuncs: 유연한 연산 제공

In [6]:
# 난수 배열 2개 생성
np.random.seed(1)
arr1 = np.random.randint(10, size=5)
arr2 = np.random.randint(10, size=5)

print(arr1, arr2)

[5 8 9 5 0] [0 1 7 6 9]


In [7]:
# 배열-스칼라 연산
arr1 = arr1 - 2
print(arr1)

[ 3  6  7  3 -2]


In [8]:
# 배열-배열 연산
arr3 = arr1 + arr2
print(arr3)

[ 3  7 14  9  7]


In [9]:
# 다차원 배열 연산: 2차원 배열 ** 스칼라
arr4 = np.random.randint(10, size=(3, 5))
print(arr4)

arr5 = arr4 ** 2
print(arr5)

[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [10]:
"""
    UFuncs: 산술 연산
"""

# Basic arithmetic operations on an array
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x ** 2 =", x ** 2)

# [+] 산술 연산에 대응하는 유니버설 함수
print("x + 5 =", np.add(x, 5))
print("x - 5 =", np.subtract(x, 5))
print("x * 2 =", np.multiply(x, 2))
print("x / 2 =", np.divide(x, 2))
print("x ** 2 =", np.power(x, 2))


x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x ** 2 = [0 1 4 9]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x ** 2 = [0 1 4 9]


In [11]:
"""
    UFuncs: 절댓값 계산
"""

# 절댓값 함수
x = np.array([-2, -1, 0, 1, 2])
print(np.abs(x))

# 복소수에 대한 절댓값 계산
x = np.array([3-4j, 4-3j, 2+0j, 0+1j])
print(np.abs(x))

[2 1 0 1 2]
[5. 5. 2. 1.]


In [12]:
"""
    np.linspace(start, stop, num): 선형 간격 벡터 생성
        - start: 벡터의 시작 값
        - end: 벡터의 종료 값
        - num: 생성할 값의 개수
"""

# [+][0, 100]의 범위를 가지며, 균일한 간격의 5개의 값들로 구성되는 벡터를 생성
x = np.linspace(0, 100, 5)
print(x)

[  0.  25.  50.  75. 100.]


In [13]:
# [+] [0, 100]의 범위를 가지며, [0, 10, 20, 30, ..., 100]와
# 같은 값들로 구성되는 벡터를 생성
x = np.linspace(0, 100, 11)
print(x)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [14]:
val_size = 1000

In [15]:
%timeit np.linspace(0, val_size, int(val_size/3))

30 µs ± 2.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [16]:
%timeit np.arange(0, val_size, 3)

4.77 µs ± 89.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [17]:
# 삼각함수(trigonometric functions)
theta = np.linspace(0, np.pi, 3)

print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [18]:
"""
    집계 함수: reduce()
"""

# 배열 생성
x = np.arange(1, 5)
print(x)

[1 2 3 4]


In [19]:
# [+] 덧셈 연산으로 집계
aggr = np.add.reduce(x)
print(aggr)

10


In [20]:
# [+] 곱셈 연산으로 집계
aggr = np.multiply.reduce(x)
print(aggr)

24


In [21]:
"""
    집계 함수: accumulate()
"""

# [+] 덧셈 연산으로 집계
accum = np.add.accumulate(x)
print(accum)

[ 1  3  6 10]


In [22]:
# [+] 곱셈 연산으로 집계
accum = np.multiply.accumulate(x)
print(accum)

[ 1  2  6 24]


In [23]:
# 집계 함수: sum()
np.random.seed(3)
arr = np.random.rand(1000000) # rand(): 0~1 사이의 실수 형태의 난수 배열 생성

print(arr)
print("sum =", np.sum(arr))

[0.5507979  0.70814782 0.29090474 ... 0.93033748 0.80429816 0.47400579]
sum = 500422.19897015305


In [24]:
# sum(): Python 내장함수
%timeit sum(arr)

82.1 ms ± 4.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [25]:
# np.sum()
%timeit np.sum(arr) # 1000µs = 1ms

1.6 ms ± 200 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [26]:
# [+] 그 외의 집계함수
print("max =", np.max(arr))
print("min =", np.min(arr))
print("mean =", np.mean(arr))
print("median =", np.median(arr))
print("percentile =", np.percentile(arr, 10))
print("variance =", np.var(arr))
print("standard deviation =", np.std(arr))
print("index of maximum value =", np.argmax(arr))
print("index of minimum value =", np.argmin(arr))
print("Is there any number greater than 1? =", np.any(arr > 1))
print("Is every number greater than 0? =", np.all(arr > 0)) 

max = 0.9999996367889004
min = 1.5496004267534502e-06
mean = 0.500422198970153
median = 0.5005659265960778
percentile = 0.10025999321220155
variance = 0.08331685347394581
standard deviation = 0.28864658922971154
index of maximum value = 339543
index of minimum value = 980213
Is there any number greater than 1? = False
Is every number greater than 0? = True


In [27]:
# 다차원 집계
np.random.seed(0)
arr = np.random.randint(10, size=(3, 4))
print(arr, '\n')

print(np.sum(arr, axis=0), '\n')
print(np.sum(arr, axis=1))

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 

[14 13 13 14] 

[11 24 19]
